<?php
add_action( 'wp_enqueue_scripts', 'wp_iu_scripts' );

function wp_iu_scripts() {
	wp_enqueue_script( 'wp-iu-script', get_template_directory_uri() . '/wp-image-uploader/wp-image-uploader.js', array( 'jquery' ), null, true );
	wp_localize_script( 'wp-iu-script', 'wpiu', array(
		'ajaxurl' => admin_url( 'admin-ajax.php' )
	) );
}

add_action( 'wp_ajax_wpui_upload', 'wpui_upload_callback' );
add_action( 'wp_ajax_nopriv_wpui_upload', 'wpui_upload_callback' );
function wpui_upload_callback() {
	if ( ! function_exists( 'wp_handle_upload' ) ) {
		require_once( ABSPATH . 'wp-admin/includes/file.php' );
	}
	// echo $_FILES["upload"]["name"];
	$uploadedfile     = $_FILES['file'];
	$upload_overrides = array( 'test_form' => false );
	$movefile         = wp_handle_upload( $uploadedfile, $upload_overrides );

	// echo $movefile['url'];
	if ( $movefile && ! isset( $movefile['error'] ) ) {
		echo json_encode($movefile);
	} else {
		/**
		 * Error generated by _wp_handle_upload()
		 * @see _wp_handle_upload() in wp-admin/includes/file.php
		 */
		echo $movefile['error'];
	}
	exit();
}

/**
 * выводит поле с input type file
 *
 * @param array $args
 */
function wpiu_upload_field( $args = array() ) {
	global $post;
	$args = wp_parse_args( $args, array(
		'post_id'     => $post->ID,
		'input_class' => 'fileInput',
		'input_id'    => 'file1',
		'label_class' => 'fileLabel',
		'label_text'  => 'загрузить',
		'target'      => '#image-bg',
		'hidden_name' => 'upload_file'
	) );
	echo '<input type="hidden" name="' . esc_attr( $args['hidden_name'] ) . '" data-action="change-attr" data-product-id="' . esc_attr( $args['post_id'] ) . '">';
	echo '<input type="file" class="' . esc_attr( $args['input_class'] ) . '" accept="image/*" id="' . esc_attr( $args['input_id'] ) . '" data-target="' . esc_attr( $args['target'] ) . '">';
	echo '<label for="' . esc_attr( $args['input_id'] ) . '" class="' . esc_attr( $args['label_class'] ) . '">' . esc_html( $args['label_text'] ) . '</label>';
}